name: Run CI
on: [push, pull_request]
jobs:

  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
      id: go
      
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '285.0.0'
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Check out the code
      uses: actions/checkout@v3

    # Use the JSON key in secret to login gcr.io
    - uses: 'docker/login-action@v2'
      with:
        registry: 'gcr.io' # or REGION.docker.pkg.dev
        username: '_json_key'
        password: '${{ secrets.GCR_SA_KEY }}'

    # Push image to GCR to facilitate some environments that have rate limitation to docker hub, e.g. vSphere.
    - name: Publish container image to GCR
      run: |
        sudo swapoff -a
        sudo rm -f /mnt/swapfile
        docker image prune -a --force
        REGISTRY=gcr.io/velero-gcp ./hack/docker-push.sh

    - name: Make ci
      run: make ci
